##  reference.build-ci pipeline

name: reference.build-ci
trigger:
- master

queue:
  name: Hosted VS2017
steps:
- powershell: '.\clone.ps1'

  workingDirectory: '$(System.DefaultWorkingDirectory)'

  displayName: 'clone'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    BRANCH: $(BRANCH)
