##  reference.build-ci pipeline

name: reference.build-ci
trigger:
- master

queue:
  name: Hosted VS2017
steps:
- powershell: |
    $InformationPreference = "Continue"
    Push-Location $(System.DefaultWorkingDirectory)

    if(Test-Path ./release) {
      Remove-Item ./release -Force -Recurse
    }
    $null = New-Item -ItemType directory -Path ./release -Force

    git version
    git lfs version
    git init ./release
    Push-Location ./release
    Write-Information $(Get-Location)



    Write-Information "ALL  DONE"

  workingDirectory: '$(System.DefaultWorkingDirectory)'

  displayName: 'release'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    BRANCH: $(BRANCH)
