##  reference.build-ci pipeline

name: reference.build-ci
trigger:
- master

queue:
  name: Hosted VS2017
steps:
- powershell: |
    $InformationPreference = "Continue"
    Push-Location $(System.DefaultWorkingDirectory)

    Get-Location






    Write-Information "ALL  DONE"

  workingDirectory: '$(System.DefaultWorkingDirectory)'

  displayName: 'release'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    BRANCH: $(BRANCH)
